### PR TITLE
I needed to this changes during the development

### PR DESCRIPTION
**Pull request by DevEddy**
Our app is currently in the beta, feel free to use what you need ;)

### CODE REVIEW

**Comment by larsbeck** [comment]
Hi Eddy,

thanks again for all those changes. Where can I find your app?

Lars

**Comment by DevEddy** [comment]
Hi Lars,

currently we've started a closed beta. I can invite you to the beta tester for iOS, Android or UWP. I'll need your mail address of the platforms.

Eddy

**Comment by larsbeck** [comment]
Hi Eddy,

I see. That would be lars.beckmann@gmail.com. Thanks! 

Lars

**Comment by DevEddy** [comment]
Android, iOS or UWP?

**Comment by larsbeck** [comment]
Android and UWP, sorry.

**Comment by DevEddy** [comment]
Use this link for Android to join the beta: https://play.google.com/apps/testing/com.easysmarthome.cloudmaticapp

On UWP you should find it in store 

Feedback appreciated :D

**Comment by larsbeck** [comment]
So the company you are working for is located really close :-) I live in Paderborn and have been to Bad Sassendorf a couple of times to catch a train.

I'll check out the app tomorrow. Right now the link gives me an internal server error and I wasn't able to find the uwp app at first glance, but I'll have a closer look tomorrow.

**Pull request merged**
